#ifndef __INTERFACE_H__
#define __INTERFACE_H__

//  {AB8AF19D-F042-4A5C-BED3-82491097654B}
DEFINE_GUID(GUID_DEVINTERFACE_ANCHUSB,
    0xAB8AF19D, 0xF042, 0x4A5C, 0xBE, 0xD3, 0x82, 0x49, 0x10, 0x97, 0x65, 0x4B);

#define FILE_DEVICE_ANCHUSB  0x8000

// Define Interface reference/dereference routines for
// Interfaces exported by IRP_MN_QUERY_INTERFACE

#define ANCHUSB_IOCTL(index) \
    CTL_CODE(FILE_DEVICE_ANCHUSB, index, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_ANCHUSB_BULK_IN \
    CTL_CODE(FILE_DEVICE_ANCHUSB, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ANCHUSB_BULK_OUT \
    CTL_CODE(FILE_DEVICE_ANCHUSB, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ANCHUSB_RESET_DEVICE \
    CTL_CODE(FILE_DEVICE_ANCHUSB, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // __INTRFACE_H__
